# Generated by Django 5.1.5 on 2025-07-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.CharField(max_length=200)),
                ('short_url', models.CharField(blank=True, max_length=10, unique=True)),
            ],
        ),
    ]
